CREATE TABLE IF NOT EXISTS "users" (
    id SERIAL PRIMARY KEY,
    username VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    update TIMESTAMP NOT NULL DEFAULT now(),
    created TIMESTAMP NOT NULL DEFAULT now()
);